version: '3.8'

services:
  # 汽车图片标注Web服务（简化版）
  car-img-tagger:
    build:
      context: .
      dockerfile: Dockerfile.simple
    ports:
      - "8001:8001"
    environment:
      - PYTHONPATH=/app/src
      - PYTHONUNBUFFERED=1
      - REDIS_URL=redis://redis:6379
    volumes:
      # 挂载数据目录
      - ./databases:/app/databases
      - ./processed_data:/app/processed_data
      - ./models:/app/models
      - ./output:/app/output
      - ./reports:/app/reports
      # 挂载图片素材目录
      - ./图片素材:/app/图片素材
      - ./各标签素材:/app/各标签素材
    depends_on:
      - redis
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    networks:
      - car-tags-network

  # Redis缓存服务
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    command: redis-server --appendonly yes --maxmemory 128mb --maxmemory-policy allkeys-lru
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - car-tags-network

volumes:
  redis_data:
    driver: local

networks:
  car-tags-network:
    driver: bridge
