version: '3.8'

services:
  # API Gateway
  api-gateway:
    build: ./services/api-gateway
    ports:
      - "8000:8000"
    environment:
      - REDIS_URL=redis://redis:6379
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/car_tags
    depends_on:
      - redis
      - postgres
      - ai-service
      - web-service
    networks:
      - car-tags-network

  # AI推理服务
  ai-service:
    build: ./services/ai-service
    environment:
      - REDIS_URL=redis://redis:6379
      - MODEL_PATH=/models
      - GPU_ENABLED=true
      - BATCH_SIZE=8
      - MAX_WORKERS=4
    volumes:
      - ./models:/models
      - ./data:/data
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    networks:
      - car-tags-network

  # Web管理服务
  web-service:
    build: ./services/web-service
    environment:
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/car_tags
      - REDIS_URL=redis://redis:6379
    depends_on:
      - postgres
      - redis
    networks:
      - car-tags-network

  # 任务队列服务
  task-queue:
    build: ./services/task-queue
    environment:
      - REDIS_URL=redis://redis:6379
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/car_tags
    depends_on:
      - redis
      - postgres
    networks:
      - car-tags-network

  # PostgreSQL数据库
  postgres:
    image: postgres:15
    environment:
      - POSTGRES_DB=car_tags
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - car-tags-network

  # Redis缓存
  redis:
    image: redis:7-alpine
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - car-tags-network

  # Nginx负载均衡
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - api-gateway
    networks:
      - car-tags-network

  # 监控服务
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - car-tags-network

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - car-tags-network

volumes:
  postgres_data:
  redis_data:
  grafana_data:

networks:
  car-tags-network:
    driver: bridge
